### ISSUE TITLE
General problems with windows path in the CLI

### ISSUE THREAD

**Issue by kytrinyx** [exercism/cli#568]
From @FabienTregan (slightly edited for typos/clarity):

Several tests fail with wrong paths. They expect a path starting with a "/", which will not occure on Windows.

```
--- FAIL: TestConfigure (0.07s)
        Error Trace:    configure_test.go:73
        Error:          Not equal: "/a" (expected)
                                != "C:\\Users\\<USER_NAME>\\a" (actual)
```

Since there were to much things I was unsure about the design, I finally corrected some tests by calling `cfg.Normalize()` on the `expectedUserConfig` during the test. This solution is not satisfping (it calls production code to modify the expected result, when the given result is generated partly by this same code) but confirms that the test is not passing because of the (currently not injectable) `Normalize()` behaviour.

The Normalize() behaviour is tested (under windows) by `user_config_windows_test.go`. 

Business rules for  
  
Is there a real intent behind name starting with a "/" under windows, or is it only there to make tests run both on linux and windows easier?

```
	// if using "/dir" on Windows
	if strings.HasPrefix(path, "/") {
		return filepath.Join(cfg.Home, filepath.Clean(path))
	}
```

It does seem likely that a windows user will start a path with '/', unless they copy/paste some CLI instruction that was intended for ios/linux ?

**Comment by kytrinyx** [comment]
This is based on a misunderstanding on my part of how the Go library implements paths for Windows.

I had read something that suggested that the Go libraries do normalization internally, so that you could operate with just forward slashes. This is clearly incorrect, but I did not have a system I could test on while developing, so was unable to verify my assumptions properly.

A quick search now brought up an article that suggests a couple of approaches for dealing with this:
https://golangcode.com/cross-platform-file-paths/

I think that it would be worth starting off by simplifying submit command as described in https://github.com/exercism/cli/issues/551 which will remove some of the complexity around guessing paths. Once we've done that and gotten it right for all platforms, then we can consider whether or not it's worth the complexity to add it back.

**Comment by kytrinyx** [comment]
@FabienTregan Would you be able to check if this is still a problem with https://github.com/exercism/cli/releases/tag/v3.0.0-alpha.10.mentors ?

**Comment by ErikSchierboom** [comment]
I've just tested the latest alpha-10.mentors version, and I can confirm the following two issues:

1. I cannot submit using a relative path. It prints the following error: `Error: not in workspace` This happens both when using a plain relative path (`mentorcism submit Raindrops.cs`), or using a more obvious relative path (`mentorcism submit .\Raindrops.cs`).
1. I cannot submit when my path doesn't exactly match that configured as my workspace. `mentorcism submit c:\Users\erikschierboom\mentorcism\kotlin\raindrops\src\main\kotlin\Raindrops.kt` fails with `Error: not in workspace`, whereas `mentorcism submit C:\Users\erikschierboom\mentorcism\kotlin\raindrops\src\main\kotlin\Raindrops.kt` succeeds.

**Comment by nywilken** [comment]
> I cannot submit using a relative path. It prints the following error: Error: not in workspace This happens both when using a plain relative path (mentorcism submit Raindrops.cs), or using a more obvious relative path (mentorcism submit .\Raindrops.cs).

@ErikSchierboom what is the response of `echo %cd%`?

When submitting relative paths we check if it’s absolute is prefixed with the user’s default workspace. If it is not an exact match you would get the error you are reporting. 

I see that we titlize the path on Windows which upper cases the drive letter. Which would may be the reason for your second issue. With that said, what is the results of running `mentorcism workspace`?

**Comment by ErikSchierboom** [comment]
@nywilken It indeed has to do with the upper-casing of the drive letter. `mentorcism workspace` outputs `C:\Users\erikschierboom\mentorcism`. If I submit `C:\Users\erikschierboom\mentorcism\kotlin\raindrops\src\main\kotlin\Raindrops.kt`, things work fine. However, changing the drive letter to be lower-case, results in the above mentioned error. This problem could be fixed by doing a case-insensitive path comparison on Windows.

As for the first issue, it is most likely caused by the exact same drive-letter casing issue. I've found [this VS Code issue](https://github.com/Microsoft/vscode/issues/9448) that mentions the drive letter on Windows being forced to lowercase. Once again, the fix would be to do a case-insensitive comparison on Windows.

**Comment by ErikSchierboom** [comment]
As a follow-up, I can confirm that when I open a command prompt from VS Code on Windows, the drive letter gets lower-cased, which is different from my workspace.

**Comment by nywilken** [comment]
@ErikSchierboom thanks for the confirmation and additional troubleshooting information. 

The case-insensitive comparison is good. I would also like to couple it with some path normalization logic to ensure that workspace path transformations are also being applied to paths passed into the cli at runtime.

**Comment by ErikSchierboom** [comment]
@nywilken Sounds good!

**Comment by kytrinyx** [comment]
I think I've gotten the relative path issues worked out today. I haven't tackled the case insensitive drive yet.

- [Download windows-32-bit](https://www.dropbox.com/s/r1bxkmgnzhpk7yl/mentorcism-windows-32bit.zip?dl=0)
- [Download windows-64-bit](https://www.dropbox.com/s/r778dzaed6ehrtu/mentorcism-windows-64bit.zip?dl=0)

This release changes it to only take a list of files as the arguments to the submit command per https://github.com/exercism/cli/issues/608

    mentorcism submit file1 file2 file3

I've done some work to resolve symlinks--I don't know if I've covered all the use cases, though.

**Comment by kytrinyx** [comment]
Ok, I don't think I fixed it... I put the branch up on AppVeyor and it's failing:

https://ci.appveyor.com/project/kytrinyx/cli/build/111

The commit that is failing is this one: 43989699bbda0ea8779ece4d6f6c7ce5fcae5e2f
in case one of you have a chance to take a look.

**Comment by ErikSchierboom** [comment]
I think there is still an issue, when a relative path is used to submit a file. If you go to [this solution](https://exercism.io/mentor/solutions/e5785326490d4f09b43d1216d4818890), the file names are all prefixed with `\\`. I've also found this behavior when downloading some of my older exercises.

**Comment by kytrinyx** [comment]
I've opened an issue to address the slashes issue: https://github.com/exercism/cli/issues/698

We also have an open issue to deal with the problems arising because we don't take into account the fact that drive names are case insensitive: https://github.com/exercism/cli/issues/637

I'm going to close this issue in favor of the other two. Thanks so much for helping figure out what is going wrong!
